# Figure 1B: spatial maps of TRBC/IGH gene expression and VDJ UMI counts.

source("analysis/figure1/R/00_setup.R")
suppressPackageStartupMessages({
  library(Seurat)
  library(patchwork)
})

add_summary_metadata <- function(obj, summary_csv, prefix) {
  # summary_csv should contain spatial_bc and count columns generated by the
  # upstream VDJ workflow. Missing spots are filled with zero so all tissue spots
  # remain plottable.
  df <- read_csv_if_exists(summary_csv, stringsAsFactors = FALSE)
  colnames(df)[1] <- "spatial_bc"
  all_spots <- rownames(obj@meta.data)
  full <- data.frame(spatial_bc = all_spots) |>
    left_join(df, by = "spatial_bc")
  full[is.na(full)] <- 0
  rownames(full) <- full$spatial_bc
  full$spatial_bc <- NULL
  colnames(full) <- paste(prefix, colnames(full), sep = "_")
  obj <- AddMetaData(obj, full)
  obj
}

plot_spatial_feature <- function(obj, feature, title, filename) {
  p <- SpatialFeaturePlot(obj, features = feature) +
    ggtitle(title) +
    theme(plot.title = element_text(hjust = 0.5, size = 10))
  save_panel(p, filename, width = 4, height = 4)
}

for (i in seq_len(nrow(sample_config))) {
  object_name <- sample_config$object_name[i]
  if (!exists(object_name)) next
  obj <- get(object_name)
  label <- sample_config$display_sample[i]

  obj <- add_summary_metadata(obj, sample_config$trb_summary_csv[i], "TRB")
  obj <- add_summary_metadata(obj, sample_config$igh_summary_csv[i], "IGH")
  assign(object_name, obj, envir = .GlobalEnv)

  # Feature names may need adjustment depending on the Seurat object gene names
  # and summary columns. These defaults match the manuscript panels.
  if ("TRBC1" %in% rownames(obj) || "TRBC2" %in% rownames(obj)) {
    trbc_feature <- intersect(c("TRBC1", "TRBC2"), rownames(obj))[1]
    plot_spatial_feature(obj, trbc_feature, paste(label, "TRBC gene expression"),
                         paste0("figure1B_", label, "_TRBC_expression.pdf"))
  }
  if (any(grepl("^IGH", rownames(obj)))) {
    igh_feature <- grep("^IGH", rownames(obj), value = TRUE)[1]
    plot_spatial_feature(obj, igh_feature, paste(label, "IGH gene expression"),
                         paste0("figure1B_", label, "_IGH_expression.pdf"))
  }

  trb_umi <- grep("^TRB_UMI_count|^TRB_UMI", colnames(obj@meta.data), value = TRUE)[1]
  igh_umi <- grep("^IGH_UMI_count|^IGH_UMI", colnames(obj@meta.data), value = TRUE)[1]
  if (!is.na(trb_umi)) plot_spatial_feature(obj, trb_umi, paste(label, "TRB UMI"), paste0("figure1B_", label, "_TRB_UMI.pdf"))
  if (!is.na(igh_umi)) plot_spatial_feature(obj, igh_umi, paste(label, "IGH UMI"), paste0("figure1B_", label, "_IGH_UMI.pdf"))
}
