# Figure S2: supplementary correlation and communication analyses.
#
# Panel map:
#   S2A: IGH cell-type abundance vs clonotype metric correlation heatmap.
#   S2B: TRB cell-type abundance vs clonotype metric correlation heatmap.
#   S2C: CellChat incoming/outgoing interaction strength summary.
#   S2D: CellChat region interaction network.
#   S2E: BAFF, MHC-II and CXCL pathway networks.
#   S2F: Ligand-receptor contribution bars for the selected pathways.
#
# Shared code:
#   S2A-B reuse figure2I_K_correlation_heatmaps.R.
#   S2C-D reuse the CellChat object generated by figure2L_cellchat_interaction_strength.R.
#   S2E-F reuse figure2M_cellchat_pathway_networks.R.

source(file.path(Sys.getenv("SPACIR_ROOT", unset = getwd()), "analysis", "figure2", "R", "00_setup.R"))
source(file.path(figure2_dir, "R", "figure2I_K_correlation_heatmaps.R"))
source(file.path(figure2_dir, "R", "figure2M_cellchat_pathway_networks.R"))

figureS2_sample_id <- "LN2"

figureS2_correlation_panels <- data.frame(
  panel = c("FigureS2A", "FigureS2B"),
  receptor = c("IGH", "TRB"),
  metric = c("Shannon", "Shannon"),
  output_tag = c("figureS2A", "figureS2B"),
  stringsAsFactors = FALSE
)

figureS2_cellchat_pathways <- c("BAFF", "MHC-II", "CXCL")

plot_figureS2_correlations <- function(sample_id = figureS2_sample_id,
                                       panel_table = figureS2_correlation_panels) {
  # Produces one heatmap per panel/receptor.
  for (i in seq_len(nrow(panel_table))) {
    plot_correlation_heatmap(
      sample_id = sample_id,
      receptor = panel_table$receptor[i],
      metric = panel_table$metric[i],
      output_tag = panel_table$output_tag[i]
    )
  }
}

plot_figureS2_interaction_summary <- function(cellchat_rds, sample_id = figureS2_sample_id) {
  # S2C/S2D are intentionally kept as CellChat-object summaries rather than
  # duplicated raw CellChat computation. Generate cellchat_rds with
  # run_cellchat_by_region() from figure2L_cellchat_interaction_strength.R.
  suppressPackageStartupMessages(library(CellChat))
  cellchat <- readRDS(cellchat_rds)
  label <- display_sample(sample_id)

  pdf(file.path(output_dir, paste0("figureS2C_", label, "_incoming_outgoing_scatter.pdf")), width = 4, height = 3)
  print(netAnalysis_signalingRole_scatter(cellchat))
  dev.off()

  pdf(file.path(output_dir, paste0("figureS2D_", label, "_region_interaction_circle.pdf")), width = 5, height = 5)
  netVisual_circle(cellchat@net$weight, weight.scale = TRUE, label.edge = FALSE)
  dev.off()

  invisible(cellchat)
}

plot_figureS2_pathways <- function(cellchat_rds, sample_id = figureS2_sample_id,
                                   pathways = figureS2_cellchat_pathways) {
  for (pathway in pathways) {
    plot_cellchat_pathway(cellchat_rds, sample_id, pathway, output_tag = "figureS2E_F")
  }
}

# Examples:
# plot_figureS2_correlations()
# plot_figureS2_interaction_summary("analysis/figure2/outputs/figure2L_LN2_cellchat.rds")
# plot_figureS2_pathways("analysis/figure2/outputs/figure2L_LN2_cellchat.rds")
